stages:
  data_load:
    cmd: python src/pipelines/load_data.py
    deps:
      - 'src/pipelines/load_data.py'
    params:
      - WORK_DIR
      - data_save_paths
    outs:
      - data/iris_data.fth
  splitting:
    cmd: python src/pipelines/split.py
    deps:
      - src/pipelines/split.py
      - data/iris_data.fth
    params:
      - WORK_DIR
      - data_save_paths
    outs:
      - data/train.fth
      - data/test.fth
  evaluation:
    cmd: python src/pipelines/evaluate.py
    deps:
      - src/pipelines/evaluate.py
      - data/train.fth
      - data/test.fth
    params:
      - WORK_DIR
      - data_save_paths
      - metrics_save_paths
      - model_params
    metrics:
      - metrics/cv_roc_auc.json
      - metrics/test_roc_auc.json
    

